<?php

namespace Tests\Feature;

use App\Models\User;
use App\Models\Transmittal;
use App\Models\Office;
use Illuminate\Support\Facades\Auth;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UATModule4_5Test extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp();
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();
        $permissions = ['view transmittals', 'create transmittals', 'receive transmittals'];
        foreach ($permissions as $permission) {
             \Spatie\Permission\Models\Permission::findOrCreate($permission);
        }
    }

    public function test_4_1_receive_via_search_id()
    {
        // Scenario: Receiver logs in, finds transmittal, marks as received.
        $senderOffice = Office::factory()->create();
        $receiverOffice = Office::factory()->create();
        $receiverUser = User::factory()->create(['office_id' => $receiverOffice->id]);
        
        $receiverUser->givePermissionTo(['receive transmittals', 'view transmittals']);
        
        // Sender creates transmittal
        $senderUser = User::factory()->create(['office_id' => $senderOffice->id]);
        $this->actingAs($senderUser);
        
        $transmittal = Transmittal::factory()->create([
            'sender_office_id' => $senderOffice->id,
            'receiver_office_id' => $receiverOffice->id,
            'status' => 'Submitted'
        ]);

        // Now Switch to Receiver
        $this->actingAs($receiverUser);

        // Receiver views the transmittal (simulating search result click)
        $response = $this->get(route('transmittals.show', $transmittal));
        $response->assertStatus(200);
        $response->assertSee('Receive'); // Check for Receive button presence if possible, or just proceed

        // Receiver clicks "Receive"
        $response = $this->patch(route('transmittals.receive', $transmittal));

        $response->assertRedirect(); // Usually back or to index
        
        $this->assertDatabaseHas('transmittals', [
            'id' => $transmittal->id,
            'status' => 'Received',
            'receiver_user_id' => $receiverUser->id
        ]);
        
        $this->assertNotNull($transmittal->fresh()->received_at);
    }

    public function test_5_1_public_track_via_qr()
    {
        // Sender creates transmittal
        $senderUser = User::factory()->create();
        $this->actingAs($senderUser);

        $transmittal = Transmittal::factory()->create([
            'status' => 'Submitted',
            // qr_token generated by factory or model boot
        ]);
        
        // Logout / act as guest
        Auth::logout(); // Ensure no user is logged in for valid public tracking test if logic checks for guests
        // Actually actingAs persists for the test instance requests unless cleared? 
        // In feature tests, 'actingAs' applies to subsequent requests.
        // To simulate guest, we can just *not* call actingAs for the GET request, BUT we called it earlier.
        // We can use $this->post('/logout') or just rely on session flushing?
        // Let's explicitly flush session or just create a new test method context if possible?
        // Actually, $this->app['auth']->logout();
        
        $this->app['auth']->logout();
        $this->assertGuest();

        $qrToken = $transmittal->qr_token;
        
        // Guest user (no login)
        $response = $this->get(route('transmittals.public-track', $qrToken));

        $response->assertStatus(200);
        $response->assertSee($transmittal->reference_number);
        $response->assertSee($transmittal->status);
    }
    
    public function test_5_2_invalid_token()
    {
         $response = $this->get(route('transmittals.public-track', 'INVALID-TOKEN-123'));
         
         $response->assertStatus(200); // Should load page but with error message
         $response->assertSee('Transmittal not found');
    }
}
